/**
 * Organisation Interface
 * 
 * This file defines the TypeScript interface for Organisation objects used throughout the application.
 * It represents client organisations (companies, businesses, etc.) within the Jezweb Hub.
 * 
 * The interface follows the Firestore document structure defined in the organisations collection.
 */

import { Timestamp } from 'firebase/firestore';

/**
 * Address interface for both billing and shipping addresses
 */
export interface Address {
  street: string;
  suburb: string;
  state: string;
  postcode: string;
  country: string;
}

/**
 * Organisation interface representing a client organisation
 */
export interface Organisation {
  organisationId: string;       // Unique identifier (auto-generated by Firestore)
  organisationName: string;     // Name of the organisation
  organisationType?: string;    // Optional: Type of organisation (e.g., "Company", "Non-profit", "Government")
  status: string;               // Organisation status ("active", "inactive", "lead", "prospect")
  primaryContactId?: string;    // Optional: Reference to the 'contactId' in the 'contacts' collection
  billingAddress?: Address;     // Optional: Billing address
  shippingAddress?: Address;    // Optional: Shipping address (if different from billing)
  industry?: string;            // Optional: Industry (e.g., "Technology", "Healthcare")
  website?: string;             // Optional: Link to the organisation's website
  notes?: string;               // Optional: General notes about the organisation
  assignedTo?: string;          // Optional: Reference to the 'userId' in the 'users' collection (account manager)
  createdAt: Timestamp;         // Creation timestamp
  updatedAt: Timestamp;         // Last update timestamp
  customFields?: {              // Optional: For any other organisation-specific data
    [fieldName: string]: any;   // Key-value pairs
  };
}

/**
 * OrganisationFormData interface for form handling
 * Similar to Organisation but with string dates for form inputs
 */
export interface OrganisationFormData {
  organisationId?: string;      // Optional for new organisations
  organisationName: string;
  organisationType?: string;
  status: string;
  primaryContactId?: string;
  billingAddress?: Address;
  shippingAddress?: Address;
  industry?: string;
  website?: string;
  notes?: string;
  assignedTo?: string;
  customFields?: {
    [fieldName: string]: any;
  };
}

/**
 * OrganisationStatus type for organisation status values
 */
export type OrganisationStatus = 'active' | 'inactive' | 'lead' | 'prospect';

/**
 * OrganisationType type for organisation type values
 */
export type OrganisationType = 'Company' | 'Non-profit' | 'Government' | 'Individual' | 'Other';