/**
 * OrganisationContact Interface
 * 
 * This file defines the TypeScript interface for OrganisationContact objects used throughout the application.
 * It represents the many-to-many relationship between organisations and contacts in the Jezweb Hub.
 * 
 * The interface follows the Firestore document structure defined in the organisation_contacts collection.
 */

import { Timestamp } from 'firebase/firestore';

/**
 * OrganisationContact interface representing the relationship between an organisation and a contact
 */
export interface OrganisationContact {
  id: string;                 // Unique identifier (auto-generated by Firestore)
  organisationId: string;     // Reference to the organisationId in the organisations collection
  contactId: string;          // Reference to the contactId in the contacts collection
  priority: number;           // Priority of the contact within the organisation (lower number = higher priority)
  role?: string;              // Optional: Role of the contact within the organisation
  isPrimary: boolean;         // Whether this is the primary contact for the organisation
  createdAt: Timestamp;       // Creation timestamp
  updatedAt: Timestamp;       // Last update timestamp
}

/**
 * OrganisationContactFormData interface for form handling
 * Similar to OrganisationContact but with optional ID and without timestamps
 */
export interface OrganisationContactFormData {
  id?: string;                // Optional for new relationships
  organisationId: string;
  contactId: string;
  priority: number;
  role?: string;
  isPrimary: boolean;
}